In [24]:
import numpy as np
import pandas as pd

In [17]:
#Numpy.1
a=np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
#у следующей строки есть какой-то более лаконичный аналог? reshape не то делает, а больше не нашел
a=np.array([[a[0,i],a[1,i]] for i in range(len(a[1]))])

mean_a=a.mean(axis=0)
mean_a

array([2. , 8.4])

In [18]:
#Numpy.2
a_centered=np.subtract(a,mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [19]:
###Numpy.3
a_centered_sp=a_centered[0].dot(a_centered[1])
a_centered_sp/=len(a[0])-1
a_centered_sp

0.960000000000001

In [20]:
###Numpy.4
np.cov(a)
#что значит транспоннированный массив?

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

In [27]:
###Pandas.1
authors = pd.DataFrame({
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
})
books = pd.DataFrame({
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]

})
authors, books

(   author_id author_name
 0          1    Тургенев
 1          2       Чехов
 2          3  Островский,
    author_id            book_title  price
 0          1           Отцы и дети    450
 1          1                 Рудин    300
 2          1     Дворянское гнездо    350
 3          2      Толстый и тонкий    500
 4          2       Дама с собачкой    450
 5          3                 Гроза    370
 6          3  Таланты и поклонники    290)

In [58]:
###Pandas.2

authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [59]:
###Pandas.3

top5 = authors_price.sort_values(by="price", inplace=False)[::-1][:5] #что делает inplace? 
#я еще забыл как взять первые или последние 5 строк, я сделал через срез, 
#P.S. я разобрался, .heads .tails
print(top5.author_name.values)

['Чехов' 'Чехов' 'Тургенев' 'Островский' 'Тургенев']


In [88]:
###Pandas.4
'''
author_stat=pd.DataFrame({
                            "author_name" : authors.author_name.values,
                          "min_price": authors_price.loc[(author_stat["author_name"]==authors_price["author_name"]),"price"]
                         })'''

authors_price[("price")].mean()

387.14285714285717